/**
 * This is where all generated mods go
 * These get generated by ScratchForge when it exports user made mods into the test envirement
 */
/**
 * @author Eric
 *
 */
package org.golde.forge.scratchforge.mods;